{
 "title": "MyTonCtrl Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_adnl",
    "label": "node_adnl",
    "query": {
     "query": "label_values(myton_all_validators,node_adnl)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_online_validators{node_adnl=\"$node_adnl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shardchains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_shardchains{node_adnl=\"$node_adnl\"}"
    }
   ]
  },
  {
   "title": "Offers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_offers_current{node_adnl=\"$node_adnl\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "myton_offers_total{node_adnl=\"$node_adnl\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Validator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Validator Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_validator_index{node_adnl=\"$node_adnl\"}"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_local_validator_wallet_balance{node_adnl=\"$node_adnl\"}"
    }
   ]
  },
  {
   "title": "MyTonCtrl Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_mytoncore_status{node_adnl=\"$node_adnl\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "group by(status) (myton_local_validator_status_info{node_adnl=\"$node_adnl\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out of sync",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "myton_local_validator_out_of_sync{node_adnl=\"$node_adnl\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last State Serialization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Blocks" } },
   "targets": [
    {
     "expr": "myton_local_validator_last_state_serialization",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "myton_load_average_1{node_adnl=\"$node_adnl\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "myton_load_average_2{node_adnl=\"$node_adnl\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "myton_load_average_3{node_adnl=\"$node_adnl\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Network Load Average (Mbit/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "myton_network_load_average_1{node_adnl=\"$node_adnl\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "myton_network_load_average_2{node_adnl=\"$node_adnl\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "myton_network_load_average_3{node_adnl=\"$node_adnl\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_ram_usage_percent{node_adnl=\"$node_adnl\"}"
    }
   ]
  },
  {
   "title": "SWAP Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myton_swap_usage_percent{node_adnl=\"$node_adnl\"}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Disk Load, Mb/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg(myton_disk_load_average_mbs{node_adnl=\"$node_adnl\"})  by(disk)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Load, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(myton_disk_usage_percent{node_adnl=\"$node_adnl\"})  by(disk)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Election Cycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } }
 ]
}