{
 "title": "Validator Balance Heatmap Dashboard",
 "time": { "from": "2025-02-20T11:50:33.999Z", "to": "2025-02-20T12:02:07.790Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pool Balance Heatmap",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pool_balance{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Pool Validator Reward Share",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TON" } },
   "targets": [
    {
     "expr": "pool_validator_reward_share{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Validator participation status",
   "type": "state-timeline",
   "description": "Validator participation status in current elections (0: not participating, 1: participating)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "validator_participation_status{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Validator participation position",
   "type": "state-timeline",
   "description": "Validator participation status in current elections (0: not participating, 1: participating)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "validator_participation_position{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Pool Stake Amount Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pool_stake_amount_sent{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Pool Validator Amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pool_validator_amount{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Validator efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "validator_efficiency{network=\"mainnet\"}",
     "legendFormat": "{{validator}}"
    }
   ]
  }
 ]
}