global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "mytonmetrics"
    scrape_interval: 1m
    static_configs:
      - targets:
          - "host.docker.internal:9140"

  - job_name: "node_exporter"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "host.docker.internal:9100"

  - job_name: "ton-validators-metrics"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "ton-validators-metrics:8000"
