- name: Install required packages for Docker (ca-certificates and curl)
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key to /etc/apt/keyrings/docker.asc
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Ensure Docker GPG key is readable by all users
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Get system architecture using dpkg
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Add Docker APT repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ dpkg_arch.stdout | trim }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache after adding Docker repository
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

